### ISSUE TITLE
Minor - More Issues

### ISSUE THREAD

**Issue by seencasey** [alexlo94/acaciajudge.com-#10]
1. TOP of Casey Judge should be aligned to TOP of page title.
2. Mail icon is clipping!
3. Social icons should be gray.
4. Main text should be smaller than navigation links.
5. Change "Casey Judge" to font "Fredericka the Great". I have alternatives if this is not possible.

**Comment by alexlo94** [comment]
1. The perceived difference in alignments is because of different fonts and font sizes. Even removing the padding that's already there, there's no easy way to align the top of the glyphs.
2. Has been fixed
3. Done.

**Comment by alexlo94** [comment]
4. Done, paragraph text is now 0.8 times the size of s0.
5. Done.
