### ISSUE TITLE
Minor: UNbold Text

### ISSUE THREAD

**Issue by seencasey** [alexlo94/acaciajudge.com-#26]
Card labels should not be bold.
Footer text should not be bold.

Additionally, card labels should be #696969, not black.

**Comment by alexlo94** [comment]
All of these are done.
For the last point, you now have access to several color utility classes that you can use in your html snippets when making posts. If you want to change the text or background color of an html element you can add the classes "color:<color>" and "background-color:<color>" to the element.

For example:
```
<div class="background-color:black">
    <p class="color:white"> This is a paragraph with black background and white text </p>
</div>
```

Would produce a paragraph with white text and black background.

The colors you have access to are the ones that have appeared in the design previously. Namely they are the following in hex:
- red: #b80000
- orange: #bd8800
- green: #00bd13
- blue: #0028b7
- purple: #8700b7
- black: #000
- gray: #696969
- white: #fff

I can change any of these colors pretty easily so let me know if you want one of them tweaked.

**Comment by seencasey** [comment]
Fixed, closing
